services:
  - type: web
    name: prompt-engineer-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: RENDER
        value: true